version: '3.4'

services:
  bookingapi:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: BookingApi/Dockerfile

  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile

  hotelroomapi:
    image: ${DOCKER_REGISTRY-}hotelroomapi
    build:
      context: .
      dockerfile: HotelRoomApi/Dockerfile

  paymentapi:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: PaymentApi/Dockerfile