version: '3.4'

services:
  bookingapi:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: BookingApi/Dockerfile

  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile

  hotelroomapi:
    image: ${DOCKER_REGISTRY-}hotelroomapi
    build:
      context: .
      dockerfile: HotelRoomApi/Dockerfile

  paymentapi:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: PaymentApi/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "15673:15672"
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
    - 8001:80

