version: '3.4'

services:
  availabilityapi:
    image: ${DOCKER_REGISTRY-}availabilityapi
    build:
      context: .
      dockerfile: AvailabilityApi/Dockerfile
    
  bookingapi:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: BookingApi/Dockerfile

  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile

  hotelapi:
    image: ${DOCKER_REGISTRY-}hotelapi
    build:
      context: .
      dockerfile: HotelApi/Dockerfile

  paymentapi:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: PaymentApi/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "15673:15672"