version: '3.4'

services:

  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile

  hotelapi:
    image: ${DOCKER_REGISTRY-}hotelapi
    build:
      context: .
      dockerfile: HotelApi/Dockerfile

  paymentapi:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: PaymentApi/Dockerfile